# Generated by Django 4.1 on 2023-09-01 21:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("item", "0002_alter_category_options_item"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="item",
            options={"ordering": ("name",)},
        ),
    ]
