# Generated by Django 4.1 on 2023-09-01 22:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("item", "0003_alter_item_options"),
    ]

    operations = [
        migrations.RenameField(
            model_name="item",
            old_name="Category",
            new_name="category",
        ),
    ]
